### ISSUE TITLE
Documentation: Add requirement for pulumi access token

### ISSUE THREAD

**Issue by TimBanks** [ContainerCraft/Kargo#23]
Installation for local dev container, after `make kind`, user is prompted for pulumi access token.

Pulumi account and valid access token should probably be listed in the requirements so that it's setup before installation.

**Comment by usrbinkat** [comment]
Corrected order of instructions on README.md and added pulumi cloud login/access token as a prereqs list item in https://github.com/ContainerCraft/Kargo/commit/43cff8a6b0e06d29069bb10cd998514fd1b46d85 

Closing in favor of addressing more pulumi state options during post MVP milestone alpha1 https://github.com/ContainerCraft/Kargo/issues/25

**Comment by usrbinkat** [comment]
Thank you for your contribution!
