### ISSUE TITLE
Feat request: official migration away from Docker

### ISSUE THREAD

**Issue by d3287t328** [ContainerCraft/Kargo#28]
I would like to request that the official client be ```podman``` or ```nerdctl``` to comply with a fully OCI compliant toolchain, I want to build containers nonroot with nonroot running processes and the cli is compatible with docker.

**Comment by usrbinkat** [comment]
Unless i'm missing something, we're only using docker cli as a dependency of the vscode devcontainers feature and I dont have much control over that.

We also use docker for starting kind kubernetes which is a more reliable experience for most people than using the kind podman backend. I'm not up to speed on nerdctl in practice right now but if you PR a proposal that replaces docker I would look at it happily.

Docker and kind will both drop as requirements once Sidero releases this RFE for a github actions runner support including qemu as a backend for local talos dev clusters which will allow us to drop kind k8s all together.

https://github.com/siderolabs/talos/issues/8242
