### ISSUE TITLE
[RFE] Enhance with OpenUnison

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/Kargo#6]
# Problem

Kargo has no auth/access control integration. Add via Open Unison.

https://openunison.github.io/documentation/ouctl/

**Comment by mlbiam** [comment]
So from our conversations on twitter/in austin i'm thinking round 1 is we deploy with GitHub integration for auth?  Now thqt you have cert-manager i'm thinking the easiest way to go is to:

1. Generate (or trust) an internal CA with cert-manager
2. deploy NGINX for `Ingress`
3. If there's a load balancer, awesome.  if not, what i'll do is deploy NGINX as a `DaemonSet` on a multi-node cluster and just add all of the nodes to DNS

That'll get cluster access working via the dashboard and CLI with auth via GitHub.  Are there other UIs?  I know ArgoCD is being integrated.  Anything else? (ie graphana, prometheus, etc?)

**Comment by usrbinkat** [comment]
Thank you for the contribution @mlbiam
